services:
  db:
    image: mysql:9.2
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: fliqt_db
      MYSQL_USER: fliqt_user
      MYSQL_PASSWORD: fliqt_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    image: fliqt-backend-image
    build: ./backend
    working_dir: /app
    command: bash /app/run_web.sh
    env_file:
      - ./backend/.env
    ports:
      - "8080:8080"

volumes:
  db_data: {}
